### 결측치 이상치 처리하기

<hr>

**결측치 확인**

1. isnull()과 sum()을 연결한 메소드 체인 사용
2. isnull() : 결측치가 있을 경우 True <-> notnull()
3. df.isnull().sum() : 결측치의 개수
4. df.isnull().mean() : 결측치의 비율
5. dropna() : 결측치 제거
- 결측치(NaN)를 포함하는 레코드(행) 제거
- how=‘any’ : 결측치가 하나라도 있으면 제거 (기본 옵션)
- how=‘all’ : 모든 행이 결측치인 경우 제거
- dropna() 사용시 index를 따로 설정하지 않은 경우 reset_index(drop=True)를
메서드 체인으로 연결해서 사용하는 것을 추천


<hr>

**결측치 대체에 가장 많이 사용되는 방법**
- 평균 또는 중앙값 또는 최빈값을 사용
- 결측치를 꼭 대체해야하는 것일까? 평균과 중앙값, 최빈값 중 어느 것을 사용할까?
- Trial and error method
- 결측치 대체에 사용가능한 다른 방법은 없을까?
- 빈번한 값으로 대체
- 분포에 따른 이상치 파악
- 범주형 변수의 결측치 대체 : 최빈값으로 대체/ ‘UNK’ 등 새로운 범주의 생성
- KNN 즉 비슷한 유형으로 대체
- 범주형인 경우 많이 나오는 것으로 대체하기도 함

**주로 사용되는 이상치 탐지 기법**

1. 백분위 (Percentile) 기준 : describe() 활용
2. STD (Standard Deviation) 기준
3. 시각화를 통한 이상치 탐지
4. .describe()를 활용한 이상치 발견 :  min/max, 25%, 75% 값의 확인 / T를 결합하여 보기 쉽도록 표시

In [2]:
import numpy as np
import pandas as pd

In [5]:
movie = pd.read_csv('0.dataSet/movie.csv')
movie

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [6]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4916 entries, 0 to 4915
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      4897 non-null   object
 1   director_name              4814 non-null   object
 2   num_critic_for_reviews     4867 non-null   float64
 3   duration                   4901 non-null   float64
 4   director_facebook_likes    4814 non-null   float64
 5   actor_3_facebook_likes     4893 non-null   float64
 6   actor_2_name               4903 non-null   object
 7   actor_1_facebook_likes     4909 non-null   float64
 8   gross                      4054 non-null   float64
 9   genres                     4916 non-null   object
 10  actor_1_name               4909 non-null   object
 11  movie_title                4916 non-null   object
 12  num_voted_users            4916 non-null   int64
 13  cast_total_facebook_likes  4916 non-null   int64
 14  actor_3_name               4893 non-null   object
 15  facenumber_in_poster       4903 non-null   float64
 16  plot_keywords              4764 non-null   object
 17  movie_imdb_link            4916 non-null   object
 18  num_user_for_reviews       4895 non-null   float64
 19  language                   4904 non-null   object
 20  country                    4911 non-null   object
 21  content_rating             4616 non-null   object
 22  budget                     4432 non-null   float64
 23  title_year                 4810 non-null   float64
 24  actor_2_facebook_likes     4903 non-null   float64
 25  imdb_score                 4916 non-null   float64
 26  aspect_ratio               4590 non-null   float64
 27  movie_facebook_likes       4916 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [8]:
movie.duration.head()

0    178.0
1    169.0
2    148.0
3    164.0
4      NaN
Name: duration, dtype: float64

In [9]:
# null 여부 확인 
movie.duration.isnull()

0       False
1       False
2       False
3       False
4        True
        ...
4911    False
4912    False
4913    False
4914    False
4915    False
Name: duration, Length: 4916, dtype: bool

In [10]:
# 특정 컬럼값만의 null 개수 합
movie.duration.isnull().sum()

15

In [11]:
# 모든 컬러의 null 개수 합
movie.isnull().sum()

color                         19
director_name                102
num_critic_for_reviews        49
duration                      15
director_facebook_likes      102
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        862
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                152
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               300
budget                       484
title_year                   106
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 326
movie_facebook_likes           0
dtype: int64

In [12]:
movie.isnull().mean()

color                        0.003865
director_name                0.020749
num_critic_for_reviews       0.009967
duration                     0.003051
director_facebook_likes      0.020749
actor_3_facebook_likes       0.004679
actor_2_name                 0.002644
actor_1_facebook_likes       0.001424
gross                        0.175346
genres                       0.000000
actor_1_name                 0.001424
movie_title                  0.000000
num_voted_users              0.000000
cast_total_facebook_likes    0.000000
actor_3_name                 0.004679
facenumber_in_poster         0.002644
plot_keywords                0.030919
movie_imdb_link              0.000000
num_user_for_reviews         0.004272
language                     0.002441
country                      0.001017
content_rating               0.061025
budget                       0.098454
title_year                   0.021562
actor_2_facebook_likes       0.002644
imdb_score                   0.000000
aspect_ratio                 0.066314
movie_facebook_likes         0.000000
dtype: float64

In [13]:
movie.shape

(4916, 28)

**결측치 대체시의 권장**

1. UNK라는 표기로 값이 없음을 의미
2. 평균,최빈값,분포밀집등등...대체
3. 주의사항 : 무조건 지우고보자?는 절대 비추!!!, 대체 후에 삭제 여부 결정 권장(데이터 손실로 인한 부작용이 더 크기 때문)

In [18]:
# 결측치 삭제시 삭제되는 row의 index 까지 자동 소멸 
# 해결책 : 가급적 re index 작업 권장

# m = movie.dropna()
m = movie.dropna().reset_index()
m.shape

(3655, 29)

In [19]:
m

,index,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3650,4899,Color,Olivier Assayas,81.0,110.0,107.0,45.0,Béatrice Dalle,576.0,136007.0,...,39.0,French,France,R,4500.0,2004.0,133.0,6.9,2.35,171
3651,4900,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,...,26.0,Persian,Iran,Not Rated,10000.0,2000.0,0.0,7.5,1.85,697
3652,4906,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,...,371.0,English,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000
3653,4908,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
3654,4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [20]:
movie.shape

(4916, 28)

In [21]:
movie.describe()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4867.000000,4901.000000,4814.000000,4893.000000,4909.000000,4.054000e+03,4.916000e+03,4916.000000,4903.000000,4895.000000,4.432000e+03,4810.000000,4903.000000,4916.000000,4590.000000,4916.000000
mean,137.988905,107.090798,691.014541,631.276313,6494.488491,4.764451e+07,8.264492e+04,9579.815907,1.377320,267.668846,3.654749e+07,2002.447609,1621.923516,6.437429,2.222349,7348.294142
std,120.239379,25.286015,2832.954125,1625.874802,15106.986884,6.737255e+07,1.383222e+05,18164.316990,2.023826,372.934839,1.002427e+08,12.453977,4011.299523,1.127802,1.402940,19206.016458
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,49.000000,93.000000,7.000000,132.000000,607.000000,5.019656e+06,8.361750e+03,1394.750000,0.000000,64.000000,6.000000e+06,1999.000000,277.000000,5.800000,1.850000,0.000000
50%,108.000000,103.000000,48.000000,366.000000,982.000000,2.504396e+07,3.313250e+04,3049.000000,1.000000,153.000000,1.985000e+07,2005.000000,593.000000,6.600000,2.350000,159.000000
75%,191.000000,118.000000,189.750000,633.000000,11000.000000,6.110841e+07,9.377275e+04,13616.750000,2.000000,320.500000,4.300000e+07,2011.000000,912.000000,7.200000,2.350000,2000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,4.200000e+09,2016.000000,137000.000000,9.500000,16.000000,349000.000000

In [22]:
movie.describe().T

,count,mean,std,min,25%,50%,75%,max
num_critic_for_reviews,4867.0,1.379889e+02,1.202394e+02,1.00,49.00,108.00,191.00,8.130000e+02
duration,4901.0,1.070908e+02,2.528602e+01,7.00,93.00,103.00,118.00,5.110000e+02
director_facebook_likes,4814.0,6.910145e+02,2.832954e+03,0.00,7.00,48.00,189.75,2.300000e+04
actor_3_facebook_likes,4893.0,6.312763e+02,1.625875e+03,0.00,132.00,366.00,633.00,2.300000e+04
actor_1_facebook_likes,4909.0,6.494488e+03,1.510699e+04,0.00,607.00,982.00,11000.00,6.400000e+05
gross,4054.0,4.764451e+07,6.737255e+07,162.00,5019656.25,25043962.00,61108412.75,7.605058e+08
num_voted_users,4916.0,8.264492e+04,1.383222e+05,5.00,8361.75,33132.50,93772.75,1.689764e+06
cast_total_facebook_likes,4916.0,9.579816e+03,1.816432e+04,0.00,1394.75,3049.00,13616.75,6.567300e+05
facenumber_in_poster,4903.0,1.377320e+00,2.023826e+00,0.00,0.00,1.00,2.00,4.300000e+01
num_user_for_reviews,4895.0,2.676688e+02,3.729348e+02,1.00,64.00,153.00,320.50,5.060000e+03
budget,4432.0,3.654749e+07,1.002427e+08,218.00,6000000.00,19850000.00,43000000.00,4.200000e+09
title_year,4810.0,2.002448e+03,1.245398e+01,1916.00,1999.00,2005.00,2011.00,2.016000e+03
actor_2_facebook_likes,4903.0,1.621924e+03,4.011300e+03,0.00,277.00,593.00,912.00,1.370000e+05
imdb_score,4916.0,6.437429e+00,1.127802e+00,1.60,5.80,6.60,7.20,9.500000e+00
aspect_ratio,4590.0,2.222349e+00,1.402940e+00,1.18,1.85,2.35,2.35,1.600000e+01
movie_facebook_likes,4916.0,7.348294e+03,1.920602e+04,0.00,0.00,159.00,2000.00,3.490000e+05

**이상치를 결측치로 간주 하라는 견해**

1. 너무 지나치게 극단 데이터라면 데이터값을 가공(대체)
2. 결측치도 무조건 삭제전에 대체 해서 가공 후에 검증후에도 불필요하다면 삭제 권장

In [25]:
movie.duration.describe()

count    4901.000000
mean      107.090798
std        25.286015
min         7.000000
25%        93.000000
50%       103.000000
75%       118.000000
max       511.000000
Name: duration, dtype: float64

In [23]:
# 영화 상영시간  50이하는 다 50, 150보다 크다면 다 150으로 변경해 보기 
movie.duration

0       178.0
1       169.0
2       148.0
3       164.0
4         NaN
        ...
4911     87.0
4912     43.0
4913     76.0
4914    100.0
4915     90.0
Name: duration, Length: 4916, dtype: float64

In [24]:
movie.duration.clip(lower=50, upper=150)

0       150.0
1       150.0
2       148.0
3       150.0
4         NaN
        ...
4911     87.0
4912     50.0
4913     76.0
4914    100.0
4915     90.0
Name: duration, Length: 4916, dtype: float64